name: weather_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
    
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0


 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
  

  


flutter_assets:
  assets_path: assets/images/
  output_path: lib/resources/
  filename: app_images.dart
  field_prefix: